### ISSUE TITLE
Roadmap to v0.1

### ISSUE THREAD

**Issue by mahesh-hegde** [dart-lang/jnigen#42]
v0.1 is probably 2-3 weeks from now. This repo is at proof of concept stage.

Here is list of things to be handled before v0.1:

- [x] Implement log levels (`info, debug, warning, error`).

- [x] Refactor `package:jni` so that `JlObject` will be boundary between type-safe bindings and non-type-safe reflective code. `newInstance()` and friends should return `JlObject`. (I have 70% of this done on a local branch).

- [x] Implement and document usage modes (4-5)
  - [x] In-app java code
  - [x] standalone library with JARs
  - [x] Android-specific plugin wrapping android libraries

**Comment by mahesh-hegde** [comment]
cc @dcharkes

**Comment by dcharkes** [comment]
I think we should aim to release a v0.1 next week, on september 8 or 9. Then we have until september 12th to do a second release before the deadline. https://developers.google.com/open-source/gsoc/timeline

Of course we can continue adding new features after the GSoC deadline 🚀 , but for GSoC it is nice to have a published package to show off!

I think the one thing that we _really_ need to do before a v0.1 release is change jni_gen to jnigen. All the other things are nice to have, but not necessarily needed. We have pdfbox already working, so it is in a state where developers can play around with it and start giving us feedback.
